#!/usr/bin/env python3

print("FIX SUMMARY")
print("=" * 60)
print()
print("ISSUE: Test 'projet refuse si pas en attente de financement' fails")
print("because it expects a validation error but gets an authorization error.")
print()
print("ROOT CAUSE:")
print("1. ProjetController.mettreEnCours calls authorize() first")
print("2. ProjetPolicy.mettreEnCours returns false for projects not in EnAttenteFinancement")
print("3. This causes AuthorizationException instead of ValidationException")
print("4. Test expects ValidationException in session")
print()
print("SOLUTION:")
print("1. Move validation logic from ProjetPolicy.mettreEnCours to ProjetService")
print("2. Update ProjetController.mettreEnCours to call verifierConditionsMettreEnCours")
print("3. ProjetService.mettreEnCours should validate project status before mise en cours")
print()
print("This ensures:")
print("- Authorization is handled by policies only")
print("- Business logic validation is handled by services")
print("- Tests can validate service logic independently")
print("- Error handling is consistent (ValidationException)")
