#!/usr/bin/env python3

# Understand the flow of the ProjetController.mettreEnCours method

print("ProjetController.mettreEnCours method flow:")
print("1. $this->authorize('mettreEnCours', $projet);")
print("   - Calls ProjetPolicy.mettreEnCours")
print("   - Returns true if user is DAF and project status is EnAttenteFinancement")
print("   - Returns false otherwise")
print("   - If false, Laravel throws AuthorizationException")
print()
print("2. $projet->loadMissing('conventions');")
print("   - Loads conventions for the project")
print()
print("3. $this->projetService->verifierConditionsMettreEnCours($projet);")
print("   - Calls ProjetService.verifierConditionsMettreEnCours")
print("   - Calls ProjetService.getBlockersMettreEnCours")
print("   - If blocker is not null, throws ValidationException")
print()
print("4. $this->projetService->mettreEnCours($projet, auth()->user());")
print("   - Calls ProjetService.mettreEnCours")
print("   - Updates project status to EnCours")
print()
print("Test scenario:")
print("1. Project created with EnAttenteFinancement status")
print("2. Convention created with Active status")
print("3. Project manually updated to EnCours status")
print("4. API call to mise en cours the project")
print("5. Expected: ValidationException with 'projet' key in session")
print()
print("Issue:")
print("- Step 1 (authorize) will fail because project status is EnCours")
print("- This prevents steps 3 and 4 from being reached")
print("- Instead of a ValidationException, we get an AuthorizationException")
print("- The test expects a ValidationException in the session")
print()
print("Solution:")
print("- Remove the authorization check from ProjetController.mettreEnCours")
print("- Let ProjetService.mettreEnCours handle the validation")
print("- ProjetService.mettreEnCours should call ProjetService.verifierConditionsMettreEnCours")
print("- This way, validation happens at the service layer")
